"""
Main program module (PlainText Context version)

Responsible for orchestration and execution of NEV company investment analysis tasks.
Differences from the Structured Context version:
- Uses plain text to pass context and instructions
- Uses simplified task scheduling logic
- Main agent dynamically generates execution instructions through LLM
Key functions:
- Defines 8 analysis steps and their dependency relationships
- Dynamically generates sub-agent execution instructions
- Manages global state and task results
- Produces final report and performance metrics
"""

import os
from datetime import datetime
from agents import run_sub_agent
from config import client
from evaluator import evaluate_by_master
from metrics import add_usage, finish_run_stats, get_run_stats, reset_run_stats

#ENABLE_EVAL = os.getenv("ENABLE_EVAL", "1") == "1"
ENABLE_EVAL = True

GLOBAL_TASK_DESCRIPTION = (
    "Complete a comparative research report on NEV companies for investment decisions, covering financial performance, earnings quality, "
    "cost and efficiency, external ratings and market performance, policy environment, comprehensive risk, and final investment ranking. "
    "Ensure outputs at each stage can be directly reused by downstream sub-agents with consistent standards."
)

WORKFLOW = [
    {
        "agent": "sub1",
        "command": "Collect key financial data for NIO, Li Auto, XPeng, and BYD (revenue scale, gross margin, deliveries, R&D investment, cash reserves). Do not analyze; provide structured output.",
    },
    {
        "agent": "sub2",
        "command": "Based on sub1 data, analyze profitability and gross margin structure of the four companies, around 200 words per company.",
    },
    {
        "agent": "sub3",
        "command": "Based on sub1 data, analyze cost control and operational efficiency of the four companies, around 300 words per company.",
    },
    {
        "agent": "sub4",
        "command": "Integrate outputs from sub2 and sub3 to form key conclusions for the four companies, around 400 words per company.",
    },
    {
        "agent": "sub5",
        "command": "Collect broker ratings, stock performance, and expert strategic assessments from 2024 Q4 to January 2026, summarize by company in structured form, around 300 words per company.",
    },
    {
        "agent": "sub6",
        "command": "Collect news related to NEV policies from 2024 Q4 to January 2026, and summarize policy-environment changes and industry impact.",
    },
    {
        "agent": "sub7",
        "command": "Integrate sub1, sub5, and sub6 to output risk assessments for the four companies, around 200 words per company.",
    },
    {
        "agent": "sub8",
        "command": "Integrate sub4 and sub7, then provide investment recommendations and ranking for the four companies, with at least 400 words in total.",
    },
]

state = {
    "task_results": {},
    "current_agent": "",
    "retry_count": 0,
    "eval_decision": "pass",
}


def _build_previous_outputs_block(state, current_agent: str) -> str:
    task_results = state.get("task_results", {})
    parts = []
    for name, content in task_results.items():
        if not content or name == current_agent:
            continue
        full_output = content.strip()
        parts.append(f"[{name} full output]\n{full_output}")
    return "\n".join(parts) if parts else "No historical output available."


def _ensure_min_length(text: str, min_chars: int) -> str:
    """Ensure text reaches the minimum length."""
    if len(text) >= min_chars:
        return text
    padding = (
        "\nAdditional requirement: increase information density, clarify data-source standards, time ranges, and evidence for key conclusions; no need to use bullet points. "
        "Avoid vague statements so the output can be directly used for downstream sub-task integration."
    )
    merged = text + padding
    if len(merged) < min_chars:
        merged += "Please implicitly reflect the mapping among assumptions, evidence, and conclusions in the output."
    return merged


def _sanitize_llm_command(text: str) -> str:
    """Clean command text generated by the LLM."""
    cleaned = text.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()
    return cleaned


def _build_llm_command_generation_prompt(
    state,
    agent_name: str,
    base_command: str,
    global_task: str,
    retry_feedback: str = "",
) -> str:
    """Build the prompt for LLM command generation."""
    previous_outputs = _build_previous_outputs_block(state, agent_name)
    prompt = f"""You are the main agent. You now need to generate one executable command for {agent_name}.

Overall task description:
{global_task}
{WORKFLOW}

Current sub-task objective:
{base_command}

Previous sub-agent outputs (for context inheritance):
{previous_outputs}

Please generate one command with the following requirements:
1. Strictly align with the current sub-task objective without overstepping.
2. Require the sub-agent to fully leverage historical outputs from previous agents.
3. Output only the final command text without extra explanation.
4. The command text must be at least 400 characters to ensure information density and execution guidance."""

    if retry_feedback:
        prompt += (
            "\n\nMain-agent evaluation feedback (must be included in the command and require the sub-agent to fix items one by one):\n"
            f"{retry_feedback}"
        )

    return prompt


def _build_rule_based_command(
    state,
    agent_name: str,
    base_command: str,
    global_task: str,
    retry_feedback: str = "",
) -> str:
    """Build command based on rules."""
    previous_outputs = _build_previous_outputs_block(state, agent_name)
    command = f"""You are the {agent_name} execution unit assigned by the main agent. Complete the current sub-task around the overall objective, and ensure your output can be directly consumed by downstream nodes.

Overall task description:
{global_task}

Current sub-task objective:
{base_command}

Summary of previous sub-agent outputs (for inheriting context and standards):
{previous_outputs}

Execution requirements:
1. Strictly align with the overall objective and current sub-task boundary; avoid overextended writing.
2. The output does not need to use a structured format.
3. If historical outputs conflict, first explain conflict points, then provide the standard you adopt and why."""

    if retry_feedback:
        command += (
            "\n\nMain-agent evaluation feedback (you must revise item by item and redo):\n"
            f"{retry_feedback}"
        )

    return _ensure_min_length(command, 500)


def build_master_command(
    state,
    agent_name: str,
    base_command: str,
    global_task: str,
    retry_feedback: str = "",
) -> str:
    """Build main-agent execution command."""
    generator_prompt = _build_llm_command_generation_prompt(
        state=state,
        agent_name=agent_name,
        base_command=base_command,
        global_task=global_task,
        retry_feedback=retry_feedback,
    )

    try:
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content": "You are a main agent that strictly generates execution instructions."},
                {"role": "user", "content": generator_prompt},
            ],
            temperature=0.2,
        )
        add_usage(getattr(response, "usage", None))
        raw_command = response.choices[0].message.content or ""
        command = _sanitize_llm_command(raw_command)
        if command:
            return command
        print(f"[master-command] agent={agent_name}, empty llm command, fallback to rule-based.")
    except Exception as exc:
        print(f"[master-command] agent={agent_name}, llm generate failed, fallback. err={exc}")

    return _build_rule_based_command(
        state=state,
        agent_name=agent_name,
        base_command=base_command,
        global_task=global_task,
        retry_feedback=retry_feedback,
    )


print(f"[run] ENABLE_EVAL={ENABLE_EVAL}")
reset_run_stats()

for step in WORKFLOW:
    agent_name = step["agent"]
    base_command = step["command"]
    command = build_master_command(
        state=state,
        agent_name=agent_name,
        base_command=base_command,
        global_task=GLOBAL_TASK_DESCRIPTION,
    )

    while True:
        run_sub_agent(state, agent_name, command)

        if not ENABLE_EVAL:
            break

        content = state["task_results"].get(agent_name, "")
        eval_result = evaluate_by_master(
            agent_name=agent_name,
            command=base_command,
            content=content,
            retry_count=state["retry_count"],
        )

        state["retry_count"] = eval_result["retry_count"]
        state["eval_decision"] = eval_result["decision"]

        print(
            f"[master-eval] agent={agent_name}, decision={eval_result['decision']}, retry_count={state['retry_count']}"
        )

        if eval_result["decision"] in {"pass", "force_pass"}:
            break

        command = build_master_command(
            state=state,
            agent_name=agent_name,
            base_command=base_command,
            global_task=GLOBAL_TASK_DESCRIPTION,
            retry_feedback=eval_result["feedback"],
        )

finish_run_stats()
stats = get_run_stats()

sub8_output = state["task_results"].get("sub8", "")
if sub8_output:
    print("\n===== final sub8 output =====")
    print(sub8_output)

print("\n===== run metrics =====")
print(f"prompt_tokens: {stats['prompt_tokens']}")
print(f"completion_tokens: {stats['completion_tokens']}")
print(f"total_tokens: {stats['total_tokens']}")
elapsed = stats["elapsed_seconds"]
print(f"elapsed_seconds: {elapsed:.2f}" if isinstance(elapsed, float) else "elapsed_seconds: N/A")

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_file = f"{timestamp}.txt"
elapsed_text = f"{elapsed:.2f}" if isinstance(elapsed, float) else "N/A"

with open(output_file, "w", encoding="utf-8") as f:
    f.write("===== final sub8 output =====\n")
    f.write(sub8_output if sub8_output else "(empty)\n")
    f.write("\n===== run metrics =====\n")
    f.write(f"prompt_tokens: {stats['prompt_tokens']}\n")
    f.write(f"completion_tokens: {stats['completion_tokens']}\n")
    f.write(f"total_tokens: {stats['total_tokens']}\n")
    f.write(f"elapsed_seconds: {elapsed_text}\n")

print(f"saved_report: {output_file}")
